<div class="modal fade">
    <div class="modal-dialog modal-dialog-dice" id="sizeDice">
        <div class="modal-content">
            <div class="modal-body">
                <div id="diceCanvas"></div>
                <div id="resultDice" class="result-dice">
                    <table>
                        <tbody>
                            <tr>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="attempts attempt_1"></div>
                <div class="attempts attempt_2"></div>
                <div class="attempts attempt_3"></div>
                <div class="attempts attempt_4"></div>
                <div class="attempts attempt_5"></div>
                <div id="container"></div>
                <button id="buttonStart" type="button" class="btn m_btn btn-success btn-b btn-2h by-now">START</button>
            </div>
        </div>
    </div>
</div>
