<div class="modal fade">
    <div class="modal-dialog modal-lg modal-dialog-help">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
                <h4 class="modal-title"><b>Help</b></h4>
            </div>
            <div class="modal-body">
                <div class="modal-inner">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>From</label>
                                <div class="fromelement">
                                    <div class="avatar"></div>
                                    <div class="username">
                                        <a target="_blank"></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <form>
                                <div class="form-group">
                                    <label>Email</label>
                                    <input name="subject" type="email" class="form-control" placeholder="Email">
                                </div>
                                <div class="form-group">
                                    <label>Message <font color="red">*</font></label>
                                    <textarea name="message" class="form-control" rows="10"></textarea>
                                </div>
                            </form>
                        </div>
                        <div class="col-sm-6" >
                            <div class="form-group">
                                <label>Screenshot</label>
                                <canvas id="screenshotCanvas" width="100%"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Send</button>
                </div>
            </div>
        </div>
    </div>
</div>