<div class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content modal-content-noFooter">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
                <h4 class="modal-title"><b>Messages</b></h4>
            </div>
            <div class="modal-body">
                <div class="modal-inner">
                    <div class="items items-messages">
                        <div class="item">
                            <div class="preview"></div>
                            <div class="main">
                                <a class="title">Test Message</a>
                                <p class="descriptino">Some test</p>
                            </div>
                            <div class="btns">
                                <a class="btn btn-info">Claim</a>
                            </div>
                        </div>
                        <div class="item">
                            <div class="preview"></div>
                            <div class="main">
                                <a class="title">Test Message</a>
                                <p class="descriptino">Some test</p>
                            </div>
                            <div class="btns">
                                <a class="btn btn-info">Claim</a>
                            </div>
                        </div>
                        <div class="item">
                            <div class="preview"></div>
                            <div class="main">
                                <a class="title">Test Message</a>
                                <p class="descriptino">Some test</p>
                            </div>
                            <div class="btns">
                                <a class="btn btn-info">Claim</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>