<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
                <h4 class="modal-title"><b>Settings</b></h4>
            </div>
            <div class="modal-body">
                <div class="modal-inner modal-inner-white">
                    <div class="row">
                        <div class="col-sm-12">
                            <form class="form-horizontal">
                                <div class="form-group">
                                    <label class="col-sm-4 control-label">Interface language</label>
                                    <div class="col-sm-8">
                                        <div class="radio">
                                            <label>
                                              <input name="lang_code" type="radio"> English
                                            </label>
                                        </div>
                                        <div class="radio">
                                            <label>
                                              <input name="lang_code" type="radio"> Russian
                                            </label>
                                        </div>
                                        <div class="radio">
                                            <label>
                                              <input name="lang_code" type="radio"> France
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-4 control-label">Show in chat</label>
                                    <div class="col-sm-8">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox"> <b>All</b>
                                            </label>
                                        </div>
                                        <div class="checkbox">
                                            <label>
                                              <input type="checkbox"> English
                                            </label>
                                        </div>
                                        <div class="checkbox">
                                            <label>
                                              <input type="checkbox"> Russian
                                            </label>
                                        </div>
                                        <div class="checkbox">
                                            <label>
                                              <input type="checkbox"> France
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>