<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content modal-content-noFooter">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
                <h4 class="modal-title"><b>Shop</b></h4>
            </div>
            <div class="modal-body">
                <div class="modal-inner">
                    <table class="table modal-table shopList">
                        <tbody>
                            <% shopList.each(function(item){%>
                                <% if (item.get('type') != 'promo') { %>
                                    <tr data-id="<%=item.get('id')%>"  class='shopItem'>
                                        <td class="icon"><div></div></td>
                                        <td>
                                            <div class="shop-price">
                                                <b><%=item.get('title')%></b>
                                                <% if(item.get('discount')){%>
                                                <span class="esave">(was: <%=item.get('discount')%>)</span>
                                                <% } %>
                                                <!--<div class="bonus"><b>+ 100% boost d'XP pour 1 jour</b></div>-->
                                            </div>
                                            <!--<div class="plusicon text-center text-uppercase"><span>PLUS</span></div>-->
                                        </td>
                                        <td class="text-right"><b><%=item.get('price')%></b> USD</td>
                                        <td class="text-right"><a class="btn m_btn btn-warning btn-s"><b>Buy</b></a></td>
                                    </tr>
                                <% } %>
                            <% }) %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>