<table border="0" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <td style="width:810px;margin:0;padding:15px 0;direction:ltr">
                <table width="100%" border="0" cellpadding="0" cellspacing="0">
                    <tbody>
                        <tr>
                            <td style="font:13px/18px Arial,sans-serif">
                                    <center style="text-align:left;max-width:560px;width:100%">
                                        <table width="100%" border="0" cellpadding="0" cellspacing="0">
                                            <tbody>
                                                <tr>
                                                    <td style="padding:0 0 24px 0">
                                                        <span style="font:normal 20px/20px Arial,sans-serif;margin:0;color:#000000!important;padding-bottom:20px;display:block;direction:ltr">
                                                            Notification: Change email in <b><?php echo $this->site_name?></b>
                                                        </span>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                        <table width="100%" border="0" cellpadding="0" cellspacing="0">
                                            <tbody>
                                                <tr>
                                                    <td style="padding-bottom:25px;border-bottom:1px solid #e5e5e5">
                                                        <table cellpadding="0" cellspacing="0" align="left" style="direction:ltr;border-collapse:collapse">
                                                            <tbody>
                                                                <tr>
                                                                    <td>
                                                                        <table border="0" cellpadding="0" cellspacing="0">
                                                                            <tbody><tr>
                                                                                    <td>
                                                                                        Old email: <?php echo $this->userRow->email?><br/>
                                                                                        New email: <?php echo $this->userRow->email_new?>
                                                                                        <br><br>
                                                                                    </td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>
                                                                    </td>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </center>
                                <br>
                                    <center style="text-align:left;max-width:560px;width:100%">
                                        <table width="100%" border="0" cellpadding="0" cellspacing="0">
                                            <tbody>
                                                <tr>
                                                    <td colspan="2"><b>P.S:.</b><br><br></td>
                                                </tr>
                                                <tr>
                                                    <td width="90%" style="padding-bottom:40px">
                                                        Good luck!<br>
                                                        LoveBerry Team
                                                    </td>
                                                    <td style="padding-bottom:40px"><img src="<?php echo $this->basePath('img/logo-light.png')?>" width="80" height="23" alt=""></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </center>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>