<!DOCTYPE html>
<?php $v = APP_VERSION ?>
<html>
    <head>
        <title><?php echo SITE_NAME ?></title>
        <meta charset="utf-8" />
        <meta name="google" content="notranslate"/>
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css?<?php echo $v ?>" />
        <link rel="stylesheet" type="text/css" href="/css/app.css?<?php echo $v ?>" />
        <link rel="stylesheet" type="text/css" href="/css/emoticons.css?<?php echo $v ?>" />
        <link rel="stylesheet" type="text/css" href="/css/font-awesome.css?<?php echo $v ?>" />
        <!--[if gte IE 9]>
            <link rel="stylesheet" type="text/css" href="/css/ie.css?<?php echo $v ?>" />
        <![endif]-->
        <base href="<?php echo $this->basePath('/') ?>"/>
    </head>
    <body>
        <?php echo $this->content ?>
    </body>
</html>
