<!-- HEADER -->
<table class="head-wrap" bgcolor="#999999" style="width: 100%;">
    <tr>
        <td></td>
        <td class="header container" >
            <div class="content" style="padding: 15px; max-width: 600px; margin: 0 auto; display: block;">
                <table bgcolor="#999999" style="width: 100%;">
                    <tr>
                        <td><img src="http://placehold.it/200x50/" /></td>
                        <td align="right"><h6 class="collapse"><?php echo $this->servername?></h6></td>
                    </tr>
                </table>
            </div>
        </td>
        <td></td>
    </tr>
</table>
<!-- /HEADER -->